### ISSUE TITLE
Slight Jittering / Forces Real-Time to stay on

### ISSUE THREAD

**Issue by firebert85** [microdee/UE4-SpaceMouse#17]
I'm getting slight jittering in 4.25.4, it's as if a good amount of the time it's fighting to constantly reset the roll and keep the horizon straight.

Also, I'm sure the answer to this is "this is how it needs to be to work this way" but moving the spacemouse prevents me from navigating while Real-Time preview is turned off--moving the mouse always reactivates real-time. Just confirming this is a feature/requirement, and not a bug.

**Comment by Hunanbean** [comment]
As far as I know, it does require realtime and will not function in a non-realtime windows.
also, the dead-zone may be set to zero which in some can cause jittering. Maybe this will help:
Edit>Editor Preferences
Scroll down to the bottom, there will be a section called SpaceMouse>General
In this section you can see the Curve areas. I changed my dead zone start from 0 to .16 because i prefer a larger deadzone, which depending on mouse calibration could cause jittering if set too low.
Also, the 3DConnexion drivers suite does not need to be installed for this plugin to function, just so you know. (I should clarify that, that is the case unless something major has changed since the last time i examined the plug-in.)

**Comment by microdee** [comment]
Unfortunately the plugin has to enable forcefully the realtime switch, otherwise we wouldn't see the camera movement. Iirc I disable realtime after the movement is done if it was disabled before movement started, but I never gave much attention to test that part. But a jittering is odd, I have an older spacemouse pro and an older space navigator (both from 2014) they sit perfectly still when at default location and control smooth while using, I don't need to calibrate them at all. 
(I still hate 3DxWare so you still don't need their crap to use this plugin)

**Comment by microdee** [comment]
Well to this day I'm not sure what you're describing, but I've fixed a "jittering" phenomena inside the orbiting modes, so maybe that was the bug you've experienced. It'll be included within next release.

**Comment by microdee** [comment]
I think I fixed this issue with the "slight jittering". It's published in marketplace so just update from launcher, or it's release 1.1.1 on github. I'm closing this issue, if you still experience this bug in said version feel free to reopen and discuss further.
